# -*- coding: utf-8 -*-
"""SMART(TSLA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YkD4zZeU7v8qpt62xkr_OiuWhXo3bOEz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.ar_model import AutoReg

import warnings
warnings.filterwarnings('ignore')

from statsmodels.tsa.stattools import pacf

from statsmodels.tsa.arima.model import ARIMA

from statsmodels.tsa.statespace.sarimax import SARIMAX

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

import pickle

import matplotlib.font_manager as fm
from matplotlib.font_manager import FontProperties

data = yf.download('TSLA', start='2015-01-01', end='2019-12-31')
data = data.xs('TSLA', axis = 1, level = 'Ticker')
data = data['Close']

data1 = yf.download('MSFT', start='2015-01-01', end='2019-12-31')
data1 = data1.xs('MSFT', axis = 1, level = 'Ticker')
data1 = data1['Close']

def make_logdiff(df):
  df = df.reset_index()
  df = df.set_index('Date')
  df['LogDiff'] = np.log(df['Close']).diff()
  return df[['LogDiff']].dropna()

def subset_data(data, train_start, train_end, val_start, val_end, test_start, test_end):
  train = data.loc[train_start:train_end]
  val   = data.loc[val_start:val_end]
  test  = data.loc[test_start:test_end]
  return train, val, test

train, val, test = subset_data(
    data,
    train_start='2015-01-01', train_end='2017-12-31',
    val_start=  '2018-01-01',   val_end=  '2018-12-31',
    test_start= '2019-01-01',  test_end= '2019-12-31'
)

last_value = val.tail(1)
test_raw = pd.concat([last_value, test])

rp_diff = pd.concat([val.tail(1),test]).diff().dropna()

train_logdiff = make_logdiff(train)
val_logdiff   = make_logdiff(val)
test_logdiff  = make_logdiff(test_raw)

train1, val1, test1 = subset_data(
    data1,
    train_start='2015-01-01', train_end='2017-12-31',
    val_start=  '2018-01-01',   val_end=  '2018-12-31',
    test_start= '2019-01-01',  test_end= '2019-12-31'
)

rp_diff1 = pd.concat([val1.tail(1),test1]).diff().dropna()

train_logdiff1 = make_logdiff(train1)
val_logdiff1   = make_logdiff(val1)
test_logdiff1  = make_logdiff(test1)

#remember to logdiff data and then split data into subsets
rp_diff.shape

rp_diff = pd.concat([val.tail(1),test]).diff()
rp_diff.dropna(inplace=True)
rp_positive = [x for x in rp_diff if x > 0]

sum(rp_positive) #Total possible potential profit

times_font = FontProperties(fname='/content/times.ttf')
plt.title('Daily Tesla Closing Price 2015-2017', fontproperties=times_font, fontsize = 16, pad = 10)
plt.plot(train, color='#2057e7')
plt.xlabel('Date', fontproperties=times_font, fontsize = 14)
plt.ylabel('Price ($)', fontproperties=times_font, fontsize = 14)
plt.grid(True)
plt.tight_layout()
plt.xticks(rotation=45, fontproperties=times_font, fontsize = 14)
plt.yticks(fontproperties=times_font, fontsize = 14)
plt.show()

times_font = FontProperties(fname='/content/times.ttf')
plt.title('Daily Tesla Log Returns 2015-2017', fontproperties=times_font, fontsize = 16, pad = 10)
plt.plot(train_logdiff, color='#2057e7', linewidth = 1)
plt.axhline(y=0, color='black', linestyle='--', linewidth=1)
plt.xlabel('Date', fontproperties=times_font, fontsize = 14)
plt.ylabel('Log Return', fontproperties=times_font, fontsize = 14)
plt.grid(True)
plt.tight_layout()
plt.xticks(rotation=45, fontproperties=times_font, fontsize = 14)
plt.yticks(fontproperties=times_font, fontsize = 14)
plt.show()



fig, ax = plt.subplots()
plot_pacf(train_logdiff, lags=20, ax=ax)
ax.set_xticks(np.arange(0, 20, 5))
plt.show()
#7 16 26 35 (maybe like around 9-10 intervals?)
#9 10

model = AutoReg(train_logdiff, lags=1)
results = model.fit()
print("AIC:", results.aic)
#1 <- Selected
#7 AIC: -3452.6444451607417 <- Selected
#16 AIC: -3400.672539529596
#26 AIC: -3341.1235098255725
#35 AIC: -3292.0609015333985

#9 AIC: -3446.858211100735
#10 AIC: -3439.295766130371

def backtest2(train, val, test, p, q, Q, P, s):
    preds = []
    actual = []
    errors = []

    combined_train_val = pd.concat([train, val])

    for i in range(len(test)):
        current_train_data = pd.concat([combined_train_val, test.iloc[:i]])
        current_test_row = test.iloc[i:(i+1)]

        model = SARIMAX(current_train_data['LogDiff'], order=(p, 0, q), seasonal_order=(P, 0, Q, s)).fit()

        pred = model.predict(start=len(current_train_data), end=len(current_train_data))
        preds.append(pred.iloc[0])

        actual_value = current_test_row['LogDiff'].iloc[0]
        actual.append(actual_value)

        errors.append((pred.iloc[0] - actual_value)**2)

    mse = sum(errors) / len(errors)
    return mse, preds, actual

'''ARMA_mse, ARMA_preds, ARMA_actual = backtest2(train_logdiff, val_logdiff, test_logdiff, 1, 1, 0, 0, 0)'''

with open('ARMA_actual.pkl', 'rb') as f:
    actual_arma = pickle.load(f)
with open('ARMA_preds.pkl', 'rb') as f:
    preds_arma = pickle.load(f)

with open('SARMA_actual.pkl', 'rb') as f:
    actual_sarma = pickle.load(f)
with open('SARMA_preds.pkl', 'rb') as f:
    preds_sarma = pickle.load(f)

delta = np.arange(0, 0.0001, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds_arma) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

'''mse_ar, preds_ar, actual_ar = backtest2(train_logdiff, val_logdiff, test_logdiff, 1, 0, 0, 0, 0)'''

'''with open('AR_actual.pkl', 'wb') as f:
    pickle.dump(actual_ar, f)
with open('AR_preds.pkl', 'wb') as f:
    pickle.dump(preds_ar, f)'''

with open('AR_actual.pkl', 'rb') as f:
    actual_ar = pickle.load(f)
with open('AR_preds.pkl', 'rb') as f:
    preds_ar = pickle.load(f)

delta = np.arange(0, 0.0002, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds_ar) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

'''mse_sarma, preds_sarma, actual_sarma = backtest2(train_logdiff, val_logdiff, test_logdiff, 1, 1, 1, 1, 62)'''

'''res = np.array(preds_sarma) - np.array(actual_sarma)
plt.scatter(range(len(res)), res)
plt.xlabel("Time Step (Days)")
plt.ylabel("Prediction Error (Predicted - Actual LogDiff)")
plt.title("Prediction Errors Over Time (Scatter Plot)")
plt.grid(True)
plt.show()'''
#MSE 0.0009795629774798224

delta = np.arange(0, 0.0001, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds_sarma) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

profit = 0
trades = []
buy = np.array(preds_sarma) > 0.00035

for i in range(len(rp_diff)):
  if buy[i]:
    profit += rp_diff.iloc[i]
    trades.append(rp_diff.iloc[i])
  else:
    trades.append(0)

print(profit)

plt.scatter(range(len(trades)), trades)

sum(buy)
#sees all trades and their profits

delta[profits.index(max(profits))]

profit = 0
trades = []

for i in range(len(rp_diff)):
  if buy[i]:
    profit += rp_diff.iloc[i]
    trades.append(rp_diff.iloc[i])
  else:
    trades.append(0)

print('$'+ f'{profit:0.2f}')

plt.scatter(range(len(trades)), trades)

test_logdiff = pd.concat([val_logdiff.tail(5), test_logdiff])

for lag in range(1, 6):
  train_logdiff[f'Lag_{lag}'] = train_logdiff['LogDiff'].shift(lag)
  val_logdiff[f'Lag_{lag}']   = val_logdiff['LogDiff'].shift(lag)
  test_logdiff[f'Lag_{lag}']  = test_logdiff['LogDiff'].shift(lag)

train_logdiff.dropna(inplace=True)
val_logdiff.dropna(inplace=True)
test_logdiff.dropna(inplace=True)

test_logdiff.shape

train_size = train_logdiff.shape[0]
val_size   = val_logdiff.shape[0]
test_size  = test_logdiff.shape[0]

errors = []
preds = []
actual = []

combineddf = pd.concat([train_logdiff, val_logdiff])
combineddf
val_logdiff.shape

'''for i in range(1, val_size):
  train_subset = combineddf.iloc[:(i+train_size)]
  test_row = combineddf.iloc[(i+train_size):(i+train_size+1)]
  x_train = train_subset[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
  y_train = train_subset['LogDiff']
  x_test = test_row[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
  y_test = test_row['LogDiff']

  model = RandomForestRegressor(n_estimators=100, random_state=42)
  model.fit(x_train, y_train)

  pred = model.predict(x_test)[0]
  preds.append(pred)
  actual.append(y_test.values[0])

  errors.append((pred - y_test.values[0])**2)

mse = sum(errors)/len(errors)
print(f'MSE: {mse}')'''
#MSE: 0.0015345378185884083 Lag1-3
#MSE: 0.001539128190904619 Lag1-4
#MSE: 0.0015049854916112688 Lag1-5 <- Best
#MSE: 0.0015419242112663305 Lag1-6
#MSE: 0.001537328583313532 Lag1-7

#MSE: 500 trees 0.0015542007903345573
#MSE: 100 trees 0.0015508985299144413
#MSE: 50 trees 0.0015075290940528476

"""TSLA, MSFT, TBD
Find the best hyper parameters starting with PACF and ACF plots for AR, ARMA, SARIMAX, and RF for each and train on 2015-2017 to better fine tune parameters. Then backtest on 2018 to better fine tune again and then fit the final model to 2015-2018 with an expanding/rolling window going into 2019.

RF - Start lags from 3-5 and just decrease by 1 and compare MSE.

AR(p) - 1
MA(q) - 1
ARMA(p,q) - 1,1
SARIMAX(p,q,P,Q,S) - 1, 1, 1, 1, 62
RF - Lag1-5, 100 trees
"""

'''combined_train_val = pd.concat([train_logdiff, val_logdiff])

preds = []
actual = []
errors = []

for i in range(test_size):
    current_train_data = pd.concat([combined_train_val, test_logdiff.iloc[:i]])
    current_test_row = test_logdiff.iloc[i:(i+1)]
    x_train = current_train_data[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
    y_train = current_train_data['LogDiff']
    x_test = current_test_row[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
    y_test = current_test_row['LogDiff']

    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(x_train, y_train)

    pred = model.predict(x_test)[0]
    preds.append(pred)
    actual.append(y_test.values[0])

    errors.append((pred - y_test.values[0])**2)

mse = sum(errors) / len(errors)
print(f'MSE: {mse}')'''

#MSE Lag1-5 100 trees: 0.0012053086988415796 <- prob best

'''with open('RF_actual.pkl', 'wb') as f:
    pickle.dump(actual, f)
with open('RF_preds.pkl', 'wb') as f:
    pickle.dump(preds, f)'''

with open('RF_actual.pkl', 'rb') as f:
    actual = pickle.load(f)
with open('RF_preds.pkl', 'rb') as f:
    preds = pickle.load(f)

delta = np.arange(0, 0.0002, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

profit = 0
trades = []

for i in range(len(rp_diff)):
  if buy[i]:
    profit += rp_diff.iloc[i]
    trades.append(rp_diff.iloc[i])
  else:
    trades.append(0)

print('$'+ f'{profit:0.2f}')

plt.scatter(range(len(trades)), trades)

'''res = np.array(preds) - np.array(actual)
plt.scatter(range(len(res)), res)
plt.xlabel("Time Step (Days)")
plt.ylabel("Prediction Error (Predicted - Actual LogDiff)")
plt.title("Prediction Errors Over Time (Scatter Plot)")
plt.grid(True)
plt.show()'''

momentum = [False] + [True if rp_diff[i-1] > 0 else False for i in range(1, len(rp_diff))]

delta = np.arange(0, 0.0002, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = momentum

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit