# -*- coding: utf-8 -*-
"""SMART Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWV8YAw1A4dYcMJ6VseVaPR4OdpwCwyR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.ar_model import AutoReg

import warnings
warnings.filterwarnings('ignore')

from statsmodels.tsa.stattools import pacf

from statsmodels.tsa.arima.model import ARIMA

from statsmodels.tsa.statespace.sarimax import SARIMAX

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

data = yf.download('KO', start='2015-01-01', end='2019-12-31')
data = data.xs('KO', axis = 1, level = 'Ticker')
data = data['Close']
data

data = data.sort_index()
train = data.loc['2015':'2017']
train.index

val = data.loc['2018']
val.index

test = data.loc['2019']
test.index

def make_logdiff(df):
  df = df.reset_index()
  df = df.set_index('Date')
  df['LogDiff'] = np.log(df['Close']).diff()
  return df[['LogDiff']].dropna()

def subset_data(data, train_start, train_end, val_start, val_end, test_start, test_end):
  train = data.loc[train_start:train_end]
  val   = data.loc[val_start:val_end]
  test  = data.loc[test_start:test_end]
  return train, val, test

data2 = yf.download('QQQ', start='2015-01-01', end='2019-12-31')
data2 = data2.xs('QQQ', axis = 1, level = 'Ticker')
data2 = data2['Close']

train2, val2, test2 = subset_data(
    data2,
    train_start='2015-01-01', train_end='2017-12-31',
    val_start=  '2018-01-01',   val_end=  '2018-12-31',
    test_start= '2019-01-01',  test_end= '2019-12-31'
)

last_value2 = val2.tail(1)
test_raw2 = pd.concat([last_value2, test])
rp_diff2 = pd.concat([val2.tail(1),test2]).diff().dropna()

train_logdiff2 = make_logdiff(train2)
val_logdiff2   = make_logdiff(val2)
test_logdiff2  = make_logdiff(test_raw2)

test_logdiff2 = pd.concat([val_logdiff2.tail(5), test_logdiff2])

VIX = yf.download('^VIX', start='2015-01-01', end='2019-12-31')
VIX = VIX.xs('^VIX', axis = 1, level = 'Ticker')
VIX = VIX['Close']

VIX_train, VIX_val, VIX_test = subset_data(
    VIX,
    train_start='2015-01-01', train_end='2017-12-31',
    val_start=  '2018-01-01',   val_end=  '2018-12-31',
    test_start= '2019-01-01',  test_end= '2019-12-31'
)

last_VIX = VIX_val.tail(1)
VIX_test = pd.concat([last_VIX, VIX_test]).shift(1)
VIX_val = VIX_val.shift(1)
VIX_train = VIX_train.shift(1)

for lag in range(1, 6):
  train_logdiff2[f'Lag_{lag}'] = train_logdiff2['LogDiff'].shift(lag)
  val_logdiff2[f'Lag_{lag}']   = val_logdiff2['LogDiff'].shift(lag)
  test_logdiff2[f'Lag_{lag}']  = test_logdiff2['LogDiff'].shift(lag)

train_logdiff2.dropna(inplace=True)
val_logdiff2.dropna(inplace=True)
test_logdiff2.dropna(inplace=True)

VIX_train.dropna(inplace=True)
VIX_val.dropna(inplace=True)
VIX_test.dropna(inplace=True)

test_logdiff2['VIX'] = VIX_test
val_logdiff2['VIX']  = VIX_val[4:]
train_logdiff2['VIX'] = VIX_train[4:]

"""Week 1 - Work on fitting AR(q) model onto Data['LogReturn'], and figure out how to subset the data so it ends at 2017 from Data['Price']

Extra: look at yfinance package for python, and how to pull data from a specific ticker
"""

val.plot(title='KO Stock Price (2018)', figsize=(10,5))
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.grid(True)
plt.show()
#Use for comparison for the AR model below

train = train.reset_index()
train = train.set_index('Date')

train['LogDiff'] = np.log(train['Close']).diff()
train = train.dropna()
train = train.drop(columns=['Close'])
train

mod = AutoReg(train, lags = 12)
res = mod.fit()

summary = res.summary()
print(summary)

val = val.reset_index()
val = val.set_index('Date')

val['LogDiff'] = np.log(val['Close']).diff()
val = val.dropna()
val = val.drop(columns=['Close'])
val

fig, ax = plt.subplots()
plot_pacf(train['LogDiff'], lags=100, ax=ax)
ax.set_xticks(np.arange(0, 100, 5))
plt.show()
#2 3 12 22
#54 55 59 68

mod = AutoReg(train, lags = 12)
res = mod.fit()

summary = res.summary()
print(summary)

#2 AIC: -3468.3426344967656 <- Selected
#3 AIC: -3466.4673764524355
#12 AIC: -3393.7918689065177
#22 AIC: -3317.2221532530853

#54 AIC: -3069.9654679378473
#55 AIC: -3059.9053380406926
#59 AIC: -3030.9681019439067
#68 AIC: -2960.8238780943434

model = AutoReg(train['LogDiff'], lags=68)
results = model.fit()
print("AIC:", results.aic)

def create_preds(train, val, lags):
  preds = []
  true_vals = []

  for i in range(len(val)):
        current_train = pd.concat([train, val.iloc[:i]])
        model = AutoReg(current_train, lags=lags).fit()
        pred = model.predict(start=len(current_train), end=len(current_train))
        preds.append(pred.iloc[0])
        true_vals.append(val.iloc[i]['LogDiff'])

  return preds, true_vals

predictions, actual_values = create_preds(train, val, lags=12)

for i, (pred, actual) in enumerate(zip(predictions, actual_values)):
    print(f"Step {i+1}: Predicted = {pred:.4f}, Actual = {actual:.4f}")

#Did have GPT help me with this loop to see if it works

'''
preds = np.array(preds)
true_vals = np.array(true_vals)

np.mean((preds - true_vals)**2)
#Write a function to output the MSE using preds
'''

def calculate_mse(preds, true_vals):
    preds = np.array(preds)
    true_vals = np.array(true_vals)
    mse = np.mean((preds - true_vals) ** 2)
    return mse

mse_result = calculate_mse(predictions, actual_values)
print(f"The MSE is: {mse_result:.4f}")

#original np.float64(9.179762149479831e-05)

mse_result

#Create a function to take in the model validation data and the training data and then output the mean squared error
def backtest(train, val, lags):
    preds = []
    true_vals = []

    for i in range(len(val)):
      current_train = pd.concat([train, val.iloc[:i]])
      model = AutoReg(current_train, lags=lags).fit()
      pred = model.predict(start=len(current_train), end=len(current_train))
      preds.append(pred.iloc[0])
      true_vals.append(val.iloc[i]['LogDiff'])

    mse = np.mean((np.array(preds) - np.array(true_vals))**2)
    return mse

mse_value = backtest(train, val, lags=1)
print(f"The MSE from the backtest function is: {mse_value}")

#2 AIC: -3468.3426344967656 <- Selected. The MSE from the backtest function is: 8.827506158818918e-05
#3 AIC: -3466.4673764524355 The MSE from the backtest function is: 8.932874101816828e-05
#12 AIC: -3393.7918689065177 The MSE from the backtest function is: 8.919483990942207e-05
#22 AIC: -3317.2221532530853 The MSE from the backtest function is: 9.087604050113168e-05

data1 = yf.download('TSLA', start='2015-01-01', end='2019-12-31')
data1 = data1.xs('TSLA', axis = 1, level = 'Ticker')
data1 = data1['Close']
data1

data1 = data1.sort_index()
train1 = data1.loc['2015':'2017']
train1.index

test1 = data1.loc['2019']
test1.index

val1 = data1.loc['2018']
val1.index

val1.plot(title='TSLA Stock Price (2018)', figsize=(10,5))
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.grid(True)
plt.show()

train1 = train1.reset_index()
train1 = train1.set_index('Date')

train1['LogDiff'] = np.log(train1['Close']).diff()
train1 = train1.dropna()
train1 = train1.drop(columns=['Close'])
train1

mod1 = AutoReg(train1, lags = 12)
res1 = mod1.fit()

summary1 = res1.summary()
print(summary1)

val1 = val1.reset_index()
val1 = val1.set_index('Date')

val1['LogDiff'] = np.log(val1['Close']).diff()
val1 = val1.dropna()
val1 = val1.drop(columns=['Close'])
val1

fig, ax = plt.subplots()
plot_pacf(train1['LogDiff'], lags=50, ax=ax)
ax.set_xticks(np.arange(0, 50, 5))
plt.show()
#1 2 8 18

fig, ax = plt.subplots()
plot_acf(train1['LogDiff'], lags=50, ax=ax)
ax.set_xticks(np.arange(0, 50, 5))
plt.show()
#1 2 8 18

model1 = ARIMA(train1['LogDiff'], order=(18, 0, 1))
results1 = model1.fit()
print("AIC:", results1.aic)
#1,1 - AIC: -3494.68625616146 | 1,2 - AIC: -3493.3713913308375 | 1,8 - AIC: -3486.3791580690813 | 1,18 - AIC: -3475.1450062023705
#2,1 - AIC: -3493.204172407882 | 2,2 - AIC: -3491.702022141175 | 2,8 - AIC: -3484.34583727691 | 2,18 - AIC: -3473.1977268677947
#8,1 - AIC: -3485.994998485855 | 8,2 - AIC: -3484.035995931648 | 8,8 - AIC: -3485.7045093281104
#18,1 - AIC: -3473.031643889033
#1,1 | 1,2 | 2,1 | 2,2

def backtest1(train, val, p, q):
    preds = []
    true_vals = []

    for i in range(len(val)):
      current_train = pd.concat([train, val.iloc[:i]])
      model = ARIMA(current_train['LogDiff'], order=(p, 0, q)).fit()
      pred = model.predict(start=len(current_train), end=len(current_train))
      preds.append(pred.iloc[0])
      true_vals.append(val.iloc[i]['LogDiff'])

    mse = np.mean((np.array(preds) - np.array(true_vals))**2)
    return mse

'''mse_value1 = backtest1(train1, val1, 1, 1)
print(f"The MSE from the backtest function is: {mse_value1}")'''
#1,1 The MSE from the backtest function is: 0.0013411567570192954 <- Best
#1,2 The MSE from the backtest function is: 0.0013411807069866838
#2,1 The MSE from the backtest function is: 0.001343633256648092
#2,2 The MSE from the backtest function is: 0.001348723522604998

"""Write a function to susbset any given data into train,val,test

Look at SARIMA


"""

def subset_data(data, train_start, train_end, val_start, val_end, test_start, test_end):
  train = data.loc[train_start:train_end]
  val   = data.loc[val_start:val_end]
  test  = data.loc[test_start:test_end]
  return train, val, test

data2 = yf.download('WMT', start='2015-01-01', end='2019-12-31')
data2 = data2.xs('WMT', axis = 1, level = 'Ticker')
data2 = data2['Close']
data2 = data2.sort_index()

train2, val2, test2 = subset_data(
    data2,
    train_start='2015-01-01', train_end='2017-12-31',
    val_start=  '2018-01-01',   val_end=  '2018-12-31',
    test_start= '2019-01-01',  test_end= '2019-12-31'
)
data2

train2.index

val2.index

test2.index

def make_logdiff(df):
  df = df.reset_index()
  df = df.set_index('Date')
  df['LogDiff'] = np.log(df['Close']).diff()
  return df[['LogDiff']].dropna()

#val1 = val1.reset_index()
#val1 = val1.set_index('Date')
#val1['LogDiff'] = np.log(val1['Close']).diff()
#val1 = val1.dropna()
#val1 = val1.drop(columns=['Close'])

train2_logdiff = make_logdiff(train2)
val2_logdiff   = make_logdiff(val2)

val2_logdiff

fig, ax = plt.subplots()
plot_acf(train2_logdiff, lags=20, ax=ax)
plt.show()
#ACF Seasonal 18 27 50 62 150
#lower q 2 10
#PACF 1 2 | 3 18

def backtest2(train, val, p, q, Q, P, s):
    preds = []
    true_vals = []

    for i in range(len(val)):
      current_train = pd.concat([train, val.iloc[:i]])
      model = SARIMAX(current_train, order=(p, 0, q), seasonal_order=(P, 0,  Q, s), enforce_stationarity=False, enforce_invertibility=False).fit()
      pred = model.predict(start=len(current_train), end=len(current_train))
      preds.append(pred.iloc[0])
      true_vals.append(val.iloc[i])

    mse = np.mean((np.array(preds) - np.array(true_vals))**2)
    return mse

'''backtest2(train2_logdiff, val2_logdiff, 10, 1, 1, 1, 62)'''
#MSE 1, 1, 1, 1, 18 - 0.00023247582659905225
#MSE 1, 1, 1, 1, 27 - 0.00023272335701370083
#MSE 1, 1, 1, 1, 50 - 0.00023217680308604415
#MSE 1, 1, 1, 1, 62 - 0.0002315451647207026

#MSE 2, 1, 1, 1, 62 - 0.0002320096279155145
#MSE 10, 1, 1, 1, 62 - 0.0002324207830415045

data3 = yf.download('NVDA', start='2015-01-01', end='2019-12-31')
data3 = data3.xs('NVDA', axis = 1, level = 'Ticker')
data3 = data3['Close']
data3 = data3.sort_index()

train3, val3, test3 = subset_data(
    data3,
    train_start='2015-01-01', train_end='2017-12-31',
    val_start=  '2018-01-01',   val_end=  '2018-12-31',
    test_start= '2019-01-01',  test_end= '2019-12-31'
)
data3

train3_logdiff = make_logdiff(train3)
val3_logdiff   = make_logdiff(val3)

fig, ax = plt.subplots(figsize=(14, 6))  # <-- make it wider
plot_acf(train3_logdiff, lags=300, ax=ax)
plt.show()

#ACF Seasonal 13 19
#lower q
#PACF 13 19

'''backtest2(train3_logdiff, val3_logdiff, 1, 1, 1, 1, 62)'''