# -*- coding: utf-8 -*-
"""SMART(MSFT)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvqjD48dLGhnjJFu5v4YxE3KjbHO7WQ4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.ar_model import AutoReg

import warnings
warnings.filterwarnings('ignore')

from statsmodels.tsa.stattools import pacf

from statsmodels.tsa.arima.model import ARIMA

from statsmodels.tsa.statespace.sarimax import SARIMAX

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

import pickle

import matplotlib.font_manager as fm
from matplotlib.font_manager import FontProperties

data1 = yf.download('MSFT', start='2015-01-01', end='2019-12-31')
data1 = data1.xs('MSFT', axis = 1, level = 'Ticker')
data1 = data1['Close']

def make_logdiff(df):
  df = df.reset_index()
  df = df.set_index('Date')
  df['LogDiff'] = np.log(df['Close']).diff()
  return df[['LogDiff']].dropna()

def subset_data(data, train_start, train_end, val_start, val_end, test_start, test_end):
  train = data.loc[train_start:train_end]
  val   = data.loc[val_start:val_end]
  test  = data.loc[test_start:test_end]
  return train, val, test

train1, val1, test1 = subset_data(
    data1,
    train_start='2015-01-01', train_end='2017-12-31',
    val_start=  '2018-01-01',   val_end=  '2018-12-31',
    test_start= '2019-01-01',  test_end= '2019-12-31'
)

last_value = val1.tail(1)
test_raw = pd.concat([last_value, test1])

train_logdiff1 = make_logdiff(train1)
val_logdiff1   = make_logdiff(val1)
test_logdiff1  = make_logdiff(test_raw)

rp_diff = pd.concat([val1.tail(1), test1]).diff()
rp_diff.dropna(inplace=True)
rp_positive = [x for x in rp_diff if x > 0]

sum(rp_positive) #Total possible potential profit

sum(rp_diff * 0.5)

def backtest2(train, val, test, p, q, Q, P, s):
    preds = []
    actual = []
    errors = []

    combined_train_val = pd.concat([train, val])

    for i in range(len(test)):
        current_train_data = pd.concat([combined_train_val, test.iloc[:i]])
        current_test_row = test.iloc[i:(i+1)]

        model = SARIMAX(current_train_data['LogDiff'], order=(p, 0, q), seasonal_order=(P, 0, Q, s)).fit()

        pred = model.predict(start=len(current_train_data), end=len(current_train_data))
        preds.append(pred.iloc[0])

        actual_value = current_test_row['LogDiff'].iloc[0]
        actual.append(actual_value)

        errors.append((pred.iloc[0] - actual_value)**2)

    mse = sum(errors) / len(errors)
    return mse, preds, actual

'''ARMA_mse, ARMA_preds, ARMA_actual = backtest2(train_logdiff1, val_logdiff1, test_logdiff1, 1, 1, 0, 0, 0)'''

'''with open('ARMA_actual.pkl', 'wb') as f:
    pickle.dump(ARMA_actual, f)
with open('ARMA_preds.pkl', 'wb') as f:
    pickle.dump(ARMA_preds, f)'''

with open('ARMA_actual.pkl', 'rb') as f:
    actual_arma = pickle.load(f)
with open('ARMA_preds.pkl', 'rb') as f:
    preds_arma = pickle.load(f)

delta = np.arange(0, 0.0001, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds_arma) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

'''mse_ar, preds_ar, actual_ar = backtest2(train_logdiff1, val_logdiff1, test_logdiff1, 1, 0, 0, 0, 0)'''

'''with open('AR_actual.pkl', 'wb') as f:
    pickle.dump(actual_ar, f)
with open('AR_preds.pkl', 'wb') as f:
    pickle.dump(preds_ar, f)'''

with open('AR_actual.pkl', 'rb') as f:
    actual_ar = pickle.load(f)
with open('AR_preds.pkl', 'rb') as f:
    preds_ar = pickle.load(f)

delta = np.arange(0, 0.0001, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds_ar) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

'''mse_sarma, preds_sarma, actual_sarma = backtest2(train_logdiff1, val_logdiff1, test_logdiff1, 1, 1, 1, 1, 62)'''

'''with open('SARMA_actual.pkl', 'wb') as f:
    pickle.dump(actual_sarma, f)
with open('SARMA_preds.pkl', 'wb') as f:
    pickle.dump(preds_sarma, f)'''

with open('SARMA_actual.pkl', 'rb') as f:
    actual_sarma = pickle.load(f)
with open('SARMA_preds.pkl', 'rb') as f:
    preds_sarma = pickle.load(f)

delta = np.arange(0, 0.0001, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds_sarma) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

test_logdiff1 = pd.concat([val_logdiff1.tail(5), test_logdiff1])

for lag in range(1, 6):
  train_logdiff1[f'Lag_{lag}'] = train_logdiff1['LogDiff'].shift(lag)
  val_logdiff1[f'Lag_{lag}']   = val_logdiff1['LogDiff'].shift(lag)
  test_logdiff1[f'Lag_{lag}']  = test_logdiff1['LogDiff'].shift(lag)

train_logdiff1.dropna(inplace=True)
val_logdiff1.dropna(inplace=True)
test_logdiff1.dropna(inplace=True)

test_logdiff1.shape

train_size1 = train_logdiff1.shape[0]
val_size1   = val_logdiff1.shape[0]
test_size1  = test_logdiff1.shape[0]

errors = []
preds = []
actual = []

val_logdiff1.shape

combined_train_val = pd.concat([train_logdiff1, val_logdiff1])

preds = []
actual = []
errors = []

for i in range(test_size1):
    current_train_data = pd.concat([combined_train_val, test_logdiff1.iloc[:i]])
    current_test_row = test_logdiff1.iloc[i:(i+1)]
    x_train = current_train_data[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
    y_train = current_train_data['LogDiff']
    x_test = current_test_row[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
    y_test = current_test_row['LogDiff']

    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(x_train, y_train)

    pred = model.predict(x_test)[0]
    preds.append(pred)
    actual.append(y_test.values[0])

    errors.append((pred - y_test.values[0])**2)

mse = sum(errors) / len(errors)
print(f'MSE: {mse}')

combined_train_val = pd.concat([train_logdiff1, val_logdiff1])

preds = []
actual = []
errors = []

for i in range(test_size1):
    current_train_data = pd.concat([combined_train_val, test_logdiff1.iloc[:i]])
    current_test_row = test_logdiff1.iloc[i:(i+1)]
    x_train = current_train_data[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
    y_train = current_train_data['LogDiff']
    x_test = current_test_row[['Lag_1', 'Lag_2', 'Lag_3', 'Lag_4', 'Lag_5']]
    y_test = current_test_row['LogDiff']

    model = RandomForestRegressor(n_estimators=2, random_state=42, max_depth =3, max_leaf_nodes = 5, min_samples_leaf = 7)
    model.fit(x_train, y_train)

    pred = model.predict(x_test)[0]
    preds.append(pred)
    actual.append(y_test.values[0])

    errors.append((pred - y_test.values[0])**2)

mse = sum(errors) / len(errors)
print(f'MSE: {mse}')

single_tree = model.estimators_[0]

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# Get the first tree in the forest
single_tree = model.estimators_[0]

# Plot it
times_font = FontProperties(fname='/content/times.ttf')
plt.figure(figsize=(20, 10))
plot_tree(single_tree,
          feature_names=x_train.columns,
          filled=True,
          rounded=True,
          impurity=False,
          proportion=False
          )
plt.show()

'''with open('RF_actual.pkl', 'wb') as f:
    pickle.dump(actual, f)
with open('RF_preds.pkl', 'wb') as f:
    pickle.dump(preds, f)'''

with open('RF_actual.pkl', 'rb') as f:
    actual = pickle.load(f)
with open('RF_preds.pkl', 'rb') as f:
    preds = pickle.load(f)

delta = np.arange(0, 0.0002, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

momentum = [False] + [True if rp_diff[i-1] > 0 else False for i in range(1, len(rp_diff))]

delta = np.arange(0, 0.0002, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = momentum

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)

plt.scatter(delta, profits)

profit

buy_ar = np.array(preds_ar) > 0.001
buy_arma = np.array(preds_arma) > 0

time_index = test1.index
'''ar_positives = [test1[i]+1 if (buy_ar[i] == True and rp_diff[i] > 0)  else None for i in range(len(rp_diff))]
ar_negatives = [test1[i]-1 if (buy_ar[i] == True and rp_diff[i] < 0)  else None for i in range(len(rp_diff))]'''
arma_positives = [test1[i]+0.5 if (buy_arma[i] == True and rp_diff[i] > 0)  else None for i in range(len(rp_diff))]
arma_negatives = [test1[i]-0.5 if (buy_arma[i] == True and rp_diff[i] < 0)  else None for i in range(len(rp_diff))]

times_font = FontProperties(fname='/content/times.ttf')
plt.title('MSFT ARMA Model Trade Performance', fontproperties=times_font, fontsize = 16, pad = 10)
plt.plot(test1[100:180], color='#2057e7', label = 'MSFT Price')
plt.scatter(time_index[100:180], arma_positives[100:180], color = 'Green', marker = '+', s = 15, label = 'Positive Trade')
plt.scatter(time_index[100:180], arma_negatives[100:180], color = 'Red', marker = '_', s = 15, label = 'Negative Trade')
plt.xlabel('Date', fontproperties=times_font, fontsize = 14)
plt.ylabel('Price ($)', fontproperties=times_font, fontsize = 14)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.xticks(rotation=45, fontproperties=times_font, fontsize = 14)
plt.yticks(fontproperties=times_font, fontsize = 14)
plt.show()

delta = np.arange(0, 0.0001, 0.0001)

profits = []

for j in range(len(delta)):
  profit = 0
  trades = []
  buy = np.array(preds_arma) > delta[j]

  for i in range(len(rp_diff)):
    if buy[i]:
      profit += rp_diff.iloc[i]
      trades.append(rp_diff.iloc[i])
    else:
      trades.append(0)
  profits.append(profit)


from itertools import accumulate

times_font = FontProperties(fname='/content/times.ttf')
plt.title('MSFT ARMA Model Profit Over Time', fontproperties=times_font, fontsize = 16, pad = 10)
profit_over_time =  list(accumulate(trades))
plt.plot(time_index[100:180], profit_over_time[100:180], color='#2057e7')
plt.xlabel('Date', fontproperties=times_font, fontsize = 14)
plt.ylabel('Price ($)', fontproperties=times_font, fontsize = 14)
plt.grid(True)
plt.tight_layout()
plt.xticks(rotation=45, fontproperties=times_font, fontsize = 14)
plt.yticks(fontproperties=times_font, fontsize = 14)
plt.show()